services:
  postgres:
    image: postgres
    container_name: clinic-postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - clinic-postgres:/var/lib/postgresql/data
    networks:
      - clinic-network

networks:
  clinic-network:

volumes:
  clinic-postgres: