spring:
  application:
    name:
      clinic-application

  datasource:
    url: jdbc:postgresql://ep-rough-wave-a14ilngl.ap-southeast-1.aws.neon.tech/meet_med_db?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}&sslmode=require
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

okta:
  oauth2:
    audience: http://localhost:8000
    issuer: https://dev-otpcf3cma032xews.us.auth0.com/

logging:
  level:
    com:
      thanhnd: error
    root: info

auth0:
  domain: dev-otpcf3cma032xews.us.auth0.com
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  audience: https://dev-otpcf3cma032xews.us.auth0.com/api/v2/
  default-user-password: ${DEFAULT_USER_PASSWORD}


server:
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    include-message: always
  port: 8080